import {
  J2000_EPOCH,
  createOrbitalElements,
  kmToM,
} from "@teskooano/core-physics";
import {
  CelestialStatus,
  CelestialType,
  type CelestialObject,
  type PlanetProperties,
} from "@teskooano/data-types";

/**
 * Pluto configuration object for modular solar system initialization.
 */
export const pluto: CelestialObject<PlanetProperties> = {
  id: "pluto",
  name: "Pluto",
  seed: "pluto",
  type: CelestialType.PLANET,
  status: CelestialStatus.ACTIVE,
  parentId: "sun",
  realMass_kg: 1.303e22,
  realRadius_m: kmToM(1188.3),
  temperature: 44,
  albedo: 0.52,
  orbit: createOrbitalElements({
    semiMajorAxisAU: 39.482,
    eccentricity: 0.2488,
    inclinationDeg: 17.16,
    longitudeOfAscendingNodeDeg: 110.299,
    argumentOfPeriapsisDeg: 113.834,
    meanAnomalyDeg: 14.53,
    period_s: 7.82e9,
    siderealRotationPeriod_s: 5.514e5,
    axialTiltDeg: 119.51,
    aphelionAU: 49.305,
    perihelionAU: 29.658,
    averageOrbitalSpeedKmps: 4.743,
    epoch: J2000_EPOCH,
  }),
  properties: {
    type: CelestialType.PLANET,
    isMoon: false,
    composition: [
      "nitrogen ice",
      "methane ice",
      "carbon monoxide ice",
      "rocky core",
    ],
    surface: {
      roughness: 0.7,
      persistence: 0.7,
      lacunarity: 2.0,
      simplePeriod: 4.0,
      octaves: 8,
      bumpScale: 2.0,
      color1: "#F0F8FF",
      color2: "#E6E6FA",
      color3: "#D8BFD8",
      color4: "#DDA0DD",
      color5: "#E6E6FA",
      height1: 0.1,
      height2: 0.3,
      height3: 0.5,
      height4: 0.7,
      height5: 0.9,
      shininess: 25,
      specularStrength: 0.15,
      ambientLightIntensity: 0.01,
      undulation: 0.3,
      terrainType: 2,
      terrainAmplitude: 0.6,
      terrainSharpness: 1.2,
      terrainOffset: 0.0,
    },
  },
};
