import { DEG_TO_RAD, OSVector3 } from "@teskooano/core-math";
import { KM } from "@teskooano/core-physics";
import { actions } from "@teskooano/core-state";
import {
  CelestialType,
  PlanetType,
  SurfaceType,
  type PlanetProperties,
  type ProceduralSurfaceProperties,
} from "@teskooano/data-types";

const NEPTUNE_AXIAL_TILT_DEG = 28.32; // Used for Triton's axial tilt consistency

const TRITON_SMA_M = 354759 * KM;
const TRITON_SIDEREAL_ROTATION_PERIOD_S = -5.877 * 24 * 3600; // Retrograde

const NEREID_SMA_M = 5513800 * KM;
const NEREID_ORBITAL_PERIOD_S = 3.114e7;
const NEREID_SIDEREAL_ROTATION_PERIOD_S = 11.52 * 3600;

/**
 * Initializes Neptune's moons.
 * @param neptuneId The ID of Neptune.
 */
export function initializeNeptuneMoons(neptuneId: string): void {
  const defaultMoonAxialTilt = new OSVector3(0, 1, 0);

  const tritonProceduralSurface: ProceduralSurfaceProperties = {
    persistence: 0.4,
    lacunarity: 2.0,
    simplePeriod: 7.0,
    octaves: 6,
    bumpScale: 0.15,
    color1: "#D0E0F0",
    color2: "#E0F0FF",
    color3: "#F0F8FF",
    color4: "#F8FCFF",
    color5: "#FFFFFF",
    height1: 0.0,
    height2: 0.4,
    height3: 0.6,
    height4: 0.8,
    height5: 1.0,
    shininess: 0.8,
    specularStrength: 0.7,
    roughness: 0.4,
    ambientLightIntensity: 0.2,
    undulation: 0.05,
    terrainType: 1,
    terrainAmplitude: 0.1,
    terrainSharpness: 0.4,
    terrainOffset: 0.0,
  };

  const tritonAxialTiltRad = NEPTUNE_AXIAL_TILT_DEG * DEG_TO_RAD;
  actions.addCelestial({
    id: "triton",
    name: "Triton",
    seed: "triton",
    type: CelestialType.MOON,
    parentId: neptuneId,
    realMass_kg: 2.139e22,
    realRadius_m: 1353400,
    temperature: 38,
    albedo: 0.76,
    siderealRotationPeriod_s: TRITON_SIDEREAL_ROTATION_PERIOD_S,
    axialTilt: new OSVector3(
      0,
      Math.cos(tritonAxialTiltRad),
      Math.sin(tritonAxialTiltRad),
    ).normalize(), // Triton's tilt is complex, often aligned with Neptune's plane or its own orbital plane due to capture
    orbit: {
      realSemiMajorAxis_m: TRITON_SMA_M,
      eccentricity: 0.000016,
      inclination: 156.885 * DEG_TO_RAD, // Retrograde orbit
      longitudeOfAscendingNode: Math.random() * 2 * Math.PI,
      argumentOfPeriapsis: Math.random() * 2 * Math.PI,
      meanAnomaly: Math.random() * 2 * Math.PI,
      period_s: Math.abs(TRITON_SIDEREAL_ROTATION_PERIOD_S), // Absolute value for period
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ICE_WORLD,
      isMoon: true,
      parentPlanet: neptuneId,
      composition: ["nitrogen ice", "water ice", "carbon dioxide ice"],
      atmosphere: {
        composition: ["N2"], // Thin nitrogen atmosphere
        pressure: 1.4, // Very low pressure in Pascals
        glowColor: "#88AACC",
        intensity: 0.04,
        power: 0.5,
        thickness: 0.02,
      },
      surface: {
        surfaceType: SurfaceType.ICE_CRACKED, // Cantaloupe terrain, cryovolcanism

        proceduralData: {
          ...tritonProceduralSurface,
          planetType: PlanetType.ICE_WORLD,
        },
      },
    } as PlanetProperties,
  });

  const nereidProceduralSurface: ProceduralSurfaceProperties = {
    persistence: 0.45,
    lacunarity: 2.1,
    simplePeriod: 5.0,
    octaves: 5,
    bumpScale: 0.8,
    color1: "#606070",
    color2: "#808090",
    color3: "#A0A0B0",
    color4: "#C0C0D0",
    color5: "#E0E0F0",
    height1: 0.0,
    height2: 0.3,
    height3: 0.5,
    height4: 0.7,
    height5: 0.85,
    shininess: 0.15,
    specularStrength: 0.1,
    roughness: 0.7,
    ambientLightIntensity: 0.12,
    undulation: 0.05,
    terrainType: 2,
    terrainAmplitude: 0.3,
    terrainSharpness: 0.6,
    terrainOffset: 0.0,
  };

  actions.addCelestial({
    id: "nereid",
    name: "Nereid",
    seed: "nereid_seed_360",
    type: CelestialType.MOON,
    parentId: neptuneId,
    realMass_kg: 3.1e19,
    realRadius_m: 170000,
    siderealRotationPeriod_s: NEREID_SIDEREAL_ROTATION_PERIOD_S,
    axialTilt: defaultMoonAxialTilt, // Nereid has a chaotic rotation, simplified here
    orbit: {
      realSemiMajorAxis_m: NEREID_SMA_M,
      eccentricity: 0.7507, // Highly eccentric orbit
      inclination: 7.232 * DEG_TO_RAD,
      longitudeOfAscendingNode: Math.random() * 2 * Math.PI,
      argumentOfPeriapsis: Math.random() * 2 * Math.PI,
      meanAnomaly: Math.random() * 360 * DEG_TO_RAD,
      period_s: NEREID_ORBITAL_PERIOD_S,
    },
    temperature: 50,
    albedo: 0.14,
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ICE_WORLD,
      isMoon: true,
      parentPlanet: neptuneId,
      composition: ["water ice", "rock?"], // Composition is uncertain
      atmosphere: undefined, // No significant atmosphere
      surface: {
        surfaceType: SurfaceType.VARIED, // Likely cratered, but details are sparse

        proceduralData: {
          ...nereidProceduralSurface,
          planetType: PlanetType.ICE_WORLD,
        },
      },
    } as PlanetProperties,
  });

  // Proteus
  actions.addCelestial({
    id: "proteus",
    name: "Proteus",
    seed: "proteus",
    type: CelestialType.MOON,
    parentId: neptuneId,
    realMass_kg: 4.4e19,
    realRadius_m: 208000,
    temperature: 50,
    albedo: 0.1,
    siderealRotationPeriod_s: 1.122315 * 86400,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 117600 * KM,
      eccentricity: 0.0,
      inclination: 0.0,
      longitudeOfAscendingNode: 0.0,
      argumentOfPeriapsis: 276.8 * DEG_TO_RAD,
      meanAnomaly: 276.8 * DEG_TO_RAD,
      period_s: 1.122315 * 86400,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ICE_WORLD,
      isMoon: true,
      parentPlanet: neptuneId,
      composition: ["water ice", "rock"],
      surface: {
        surfaceType: SurfaceType.CRATERED,

        proceduralData: {
          color1: "#B0C4DE",
          color2: "#B0C4DE",
          color3: "#B0C4DE",
          color4: "#B0C4DE",
          color5: "#B0C4DE",
          planetType: PlanetType.ICE_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Larissa
  actions.addCelestial({
    id: "larissa",
    name: "Larissa",
    seed: "larissa",
    type: CelestialType.MOON,
    parentId: neptuneId,
    realMass_kg: 4.2e18,
    realRadius_m: 96000,
    temperature: 50,
    albedo: 0.09,
    siderealRotationPeriod_s: 0.554989 * 86400,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 73500 * KM,
      eccentricity: 0.001,
      inclination: 0.2 * DEG_TO_RAD,
      longitudeOfAscendingNode: 312.0 * DEG_TO_RAD,
      argumentOfPeriapsis: 247.3 * DEG_TO_RAD,
      meanAnomaly: 165.5 * DEG_TO_RAD,
      period_s: 0.554989 * 86400,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ICE_WORLD,
      isMoon: true,
      parentPlanet: neptuneId,
      composition: ["water ice", "rock"],
      surface: {
        surfaceType: SurfaceType.CRATERED,

        proceduralData: {
          color1: "#B0C4DE",
          color2: "#B0C4DE",
          color3: "#B0C4DE",
          color4: "#B0C4DE",
          color5: "#B0C4DE",
          planetType: PlanetType.ICE_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Galatea
  actions.addCelestial({
    id: "galatea",
    name: "Galatea",
    seed: "galatea",
    type: CelestialType.MOON,
    parentId: neptuneId,
    realMass_kg: 2.1e18,
    realRadius_m: 79000,
    temperature: 50,
    albedo: 0.08,
    siderealRotationPeriod_s: 0.428744 * 86400,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 62000 * KM,
      eccentricity: 0.0,
      inclination: 0.0,
      longitudeOfAscendingNode: 0.0,
      argumentOfPeriapsis: 86.7 * DEG_TO_RAD,
      meanAnomaly: 86.7 * DEG_TO_RAD,
      period_s: 0.428744 * 86400,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ICE_WORLD,
      isMoon: true,
      parentPlanet: neptuneId,
      composition: ["water ice", "rock"],
      surface: {
        surfaceType: SurfaceType.CRATERED,

        proceduralData: {
          color1: "#B0C4DE",
          color2: "#B0C4DE",
          color3: "#B0C4DE",
          color4: "#B0C4DE",
          color5: "#B0C4DE",
          planetType: PlanetType.ICE_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Despina
  actions.addCelestial({
    id: "despina",
    name: "Despina",
    seed: "despina",
    type: CelestialType.MOON,
    parentId: neptuneId,
    realMass_kg: 2.1e18,
    realRadius_m: 74000,
    temperature: 50,
    albedo: 0.09,
    siderealRotationPeriod_s: 0.334656 * 86400,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 52500 * KM,
      eccentricity: 0.0,
      inclination: 0.0,
      longitudeOfAscendingNode: 0.0,
      argumentOfPeriapsis: 125.1 * DEG_TO_RAD,
      meanAnomaly: 125.1 * DEG_TO_RAD,
      period_s: 0.334656 * 86400,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ICE_WORLD,
      isMoon: true,
      parentPlanet: neptuneId,
      composition: ["water ice", "rock"],
      surface: {
        surfaceType: SurfaceType.CRATERED,

        proceduralData: {
          color1: "#B0C4DE",
          color2: "#B0C4DE",
          color3: "#B0C4DE",
          color4: "#B0C4DE",
          color5: "#B0C4DE",
          planetType: PlanetType.ICE_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Thalassa
  actions.addCelestial({
    id: "thalassa",
    name: "Thalassa",
    seed: "thalassa",
    type: CelestialType.MOON,
    parentId: neptuneId,
    realMass_kg: 4.0e17,
    realRadius_m: 40000,
    temperature: 50,
    albedo: 0.09,
    siderealRotationPeriod_s: 0.311078 * 86400,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 50100 * KM,
      eccentricity: 0.0,
      inclination: 0.2 * DEG_TO_RAD,
      longitudeOfAscendingNode: 130.6 * DEG_TO_RAD,
      argumentOfPeriapsis: 165.7 * DEG_TO_RAD,
      meanAnomaly: 0.2 * DEG_TO_RAD,
      period_s: 0.311078 * 86400,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ICE_WORLD,
      isMoon: true,
      parentPlanet: neptuneId,
      composition: ["water ice", "rock"],
      surface: {
        surfaceType: SurfaceType.CRATERED,

        proceduralData: {
          color1: "#B0C4DE",
          color2: "#B0C4DE",
          color3: "#B0C4DE",
          color4: "#B0C4DE",
          color5: "#B0C4DE",
          planetType: PlanetType.ICE_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Naiad
  actions.addCelestial({
    id: "naiad",
    name: "Naiad",
    seed: "naiad",
    type: CelestialType.MOON,
    parentId: neptuneId,
    realMass_kg: 2.0e17,
    realRadius_m: 29000,
    temperature: 50,
    albedo: 0.07,
    siderealRotationPeriod_s: 0.29398 * 86400,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 48200 * KM,
      eccentricity: 0.0,
      inclination: 4.7 * DEG_TO_RAD,
      longitudeOfAscendingNode: 41.4 * DEG_TO_RAD,
      argumentOfPeriapsis: 89.7 * DEG_TO_RAD,
      meanAnomaly: 4.7 * DEG_TO_RAD,
      period_s: 0.29398 * 86400,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ICE_WORLD,
      isMoon: true,
      parentPlanet: neptuneId,
      composition: ["water ice", "rock"],
      surface: {
        surfaceType: SurfaceType.CRATERED,

        proceduralData: {
          color1: "#B0C4DE",
          color2: "#B0C4DE",
          color3: "#B0C4DE",
          color4: "#B0C4DE",
          color5: "#B0C4DE",
          planetType: PlanetType.ICE_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Halimede
  actions.addCelestial({
    id: "halimede",
    name: "Halimede",
    seed: "halimede",
    type: CelestialType.MOON,
    parentId: neptuneId,
    realMass_kg: 2.0e16,
    realRadius_m: 30000,
    temperature: 40,
    albedo: 0.04,
    siderealRotationPeriod_s: 1879 * 86400,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 16590500 * KM,
      eccentricity: 0.521,
      inclination: 119.6 * DEG_TO_RAD,
      longitudeOfAscendingNode: 198.5 * DEG_TO_RAD,
      argumentOfPeriapsis: 157.9 * DEG_TO_RAD,
      meanAnomaly: 135.8 * DEG_TO_RAD,
      period_s: 1879 * 86400,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ICE_WORLD,
      isMoon: true,
      parentPlanet: neptuneId,
      composition: ["water ice", "rock"],
      surface: {
        surfaceType: SurfaceType.CRATERED,

        proceduralData: {
          color1: "#808080",
          color2: "#808080",
          color3: "#808080",
          color4: "#808080",
          color5: "#808080",
          planetType: PlanetType.ICE_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Sao
  actions.addCelestial({
    id: "sao",
    name: "Sao",
    seed: "sao",
    type: CelestialType.MOON,
    parentId: neptuneId,
    realMass_kg: 1.0e16,
    realRadius_m: 20000,
    temperature: 40,
    albedo: 0.04,
    siderealRotationPeriod_s: 2919 * 86400,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 22239900 * KM,
      eccentricity: 0.296,
      inclination: 50.2 * DEG_TO_RAD,
      longitudeOfAscendingNode: 41.8 * DEG_TO_RAD,
      argumentOfPeriapsis: 93.5 * DEG_TO_RAD,
      meanAnomaly: 178.5 * DEG_TO_RAD,
      period_s: 2919 * 86400,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ICE_WORLD,
      isMoon: true,
      parentPlanet: neptuneId,
      composition: ["water ice", "rock"],
      surface: {
        surfaceType: SurfaceType.CRATERED,

        proceduralData: {
          color1: "#808080",
          color2: "#808080",
          color3: "#808080",
          color4: "#808080",
          color5: "#808080",
          planetType: PlanetType.ICE_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Laomedeia
  actions.addCelestial({
    id: "laomedeia",
    name: "Laomedeia",
    seed: "laomedeia",
    type: CelestialType.MOON,
    parentId: neptuneId,
    realMass_kg: 1.0e16,
    realRadius_m: 20000,
    temperature: 40,
    albedo: 0.04,
    siderealRotationPeriod_s: 3168 * 86400,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 23499900 * KM,
      eccentricity: 0.419,
      inclination: 36.9 * DEG_TO_RAD,
      longitudeOfAscendingNode: 57.6 * DEG_TO_RAD,
      argumentOfPeriapsis: 146.2 * DEG_TO_RAD,
      meanAnomaly: 248.1 * DEG_TO_RAD,
      period_s: 3168 * 86400,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ICE_WORLD,
      isMoon: true,
      parentPlanet: neptuneId,
      composition: ["water ice", "rock"],
      surface: {
        surfaceType: SurfaceType.CRATERED,

        proceduralData: {
          color1: "#808080",
          color2: "#808080",
          color3: "#808080",
          color4: "#808080",
          color5: "#808080",
          planetType: PlanetType.ICE_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Psamathe
  actions.addCelestial({
    id: "psamathe",
    name: "Psamathe",
    seed: "psamathe",
    type: CelestialType.MOON,
    parentId: neptuneId,
    realMass_kg: 2.0e15,
    realRadius_m: 20000,
    temperature: 40,
    albedo: 0.04,
    siderealRotationPeriod_s: 9149 * 86400,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 47646600 * KM,
      eccentricity: 0.413,
      inclination: 127.8 * DEG_TO_RAD,
      longitudeOfAscendingNode: 302.9 * DEG_TO_RAD,
      argumentOfPeriapsis: 148.2 * DEG_TO_RAD,
      meanAnomaly: 183.2 * DEG_TO_RAD,
      period_s: 9149 * 86400,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ICE_WORLD,
      isMoon: true,
      parentPlanet: neptuneId,
      composition: ["water ice", "rock"],
      surface: {
        surfaceType: SurfaceType.CRATERED,

        proceduralData: {
          color1: "#808080",
          color2: "#808080",
          color3: "#808080",
          color4: "#808080",
          color5: "#808080",
          planetType: PlanetType.ICE_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Neso
  actions.addCelestial({
    id: "neso",
    name: "Neso",
    seed: "neso",
    type: CelestialType.MOON,
    parentId: neptuneId,
    realMass_kg: 2.0e15,
    realRadius_m: 30000,
    temperature: 40,
    albedo: 0.04,
    siderealRotationPeriod_s: 9805 * 86400,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 49897800 * KM,
      eccentricity: 0.455,
      inclination: 128.4 * DEG_TO_RAD,
      longitudeOfAscendingNode: 55.4 * DEG_TO_RAD,
      argumentOfPeriapsis: 89.8 * DEG_TO_RAD,
      meanAnomaly: 13.8 * DEG_TO_RAD,
      period_s: 9805 * 86400,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ICE_WORLD,
      isMoon: true,
      parentPlanet: neptuneId,
      composition: ["water ice", "rock"],
      surface: {
        surfaceType: SurfaceType.CRATERED,

        proceduralData: {
          color1: "#808080",
          color2: "#808080",
          color3: "#808080",
          color4: "#808080",
          color5: "#808080",
          planetType: PlanetType.ICE_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Hippocamp
  actions.addCelestial({
    id: "hippocamp",
    name: "Hippocamp",
    seed: "hippocamp",
    type: CelestialType.MOON,
    parentId: neptuneId,
    realMass_kg: 2.0e14,
    realRadius_m: 17000,
    temperature: 40,
    albedo: 0.1,
    siderealRotationPeriod_s: 0.95039 * 86400,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 105300 * KM,
      eccentricity: 0.001,
      inclination: 0.3 * DEG_TO_RAD,
      longitudeOfAscendingNode: 0.5 * DEG_TO_RAD,
      argumentOfPeriapsis: 346.4 * DEG_TO_RAD,
      meanAnomaly: 286.5 * DEG_TO_RAD,
      period_s: 0.95039 * 86400,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ICE_WORLD,
      isMoon: true,
      parentPlanet: neptuneId,
      composition: ["water ice", "rock"],
      surface: {
        surfaceType: SurfaceType.CRATERED,

        proceduralData: {
          color1: "#B0C4DE",
          color2: "#B0C4DE",
          color3: "#B0C4DE",
          color4: "#B0C4DE",
          color5: "#B0C4DE",
          planetType: PlanetType.ICE_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });
}
