import { createOrbitalElements, kmToM } from "@teskooano/core-physics";
import {
  CelestialType,
  PlanetType,
  CelestialStatus,
  type CelestialObject,
  type PlanetProperties,
} from "@teskooano/data-types";

/**
 * Deimos moon configuration object for modular solar system initialization.
 */
export const deimos: CelestialObject<PlanetProperties> = {
  id: "deimos",
  name: "Deimos",
  seed: "deimos_dread_mars_moon",
  type: CelestialType.MOON,
  status: CelestialStatus.ACTIVE,
  parentId: "mars",
  realMass_kg: 1.51e15,
  realRadius_m: kmToM(6.27),
  temperature: 233,
  albedo: 0.068,
  orbit: createOrbitalElements({
    semiMajorAxisAU: 0.000156,
    eccentricity: 0.00033,
    inclinationDeg: 0.93,
    longitudeOfAscendingNodeDeg: 54.3,
    argumentOfPeriapsisDeg: 0.0,
    meanAnomalyDeg: 205.0,
    period_s: 30.312 * 3600,
    siderealRotationPeriod_s: 30.312 * 3600,
    axialTiltDeg: 0,
    epoch: "JD 2456191.5",
  }),
  properties: {
    type: CelestialType.MOON,
    classType: PlanetType.ROCKY,
    isMoon: true,
    composition: [
      "C-type carbonaceous chondrite",
      "D-type asteroid material",
      "thick regolith layer",
      "meteoroid impact debris",
    ],
    shapeModel: "asteroid",
    atmosphere: undefined,
    surface: {
      roughness: 0.6,
      persistence: 0.45,
      lacunarity: 2.1,
      simplePeriod: 4.0,
      octaves: 5,
      bumpScale: 0.15,
      color1: "#606060",
      color2: "#707070",
      color3: "#808080",
      color4: "#909090",
      color5: "#A0A0A0",
      height1: 0.0,
      height2: 0.25,
      height3: 0.5,
      height4: 0.75,
      height5: 1.0,
      shininess: 0.01,
      specularStrength: 0.01,
      ambientLightIntensity: 0.01,
      undulation: 0.2,
      terrainType: 1,
      terrainAmplitude: 0.3,
      terrainSharpness: 0.6,
      terrainOffset: 0.0,
    },
  },
};
