import {
  createOrbitalElements,
  J2000_EPOCH,
  kmToM,
} from "@teskooano/core-physics";
import {
  type CelestialObject,
  CelestialStatus,
  CelestialType,
  PlanetType,
  type PlanetProperties,
} from "@teskooano/data-types";

/**
 * Mars configuration object for modular solar system initialization.
 */
export const mars: CelestialObject<PlanetProperties> = {
  id: "mars",
  name: "Mars",
  seed: "mars",
  type: CelestialType.PLANET,
  status: CelestialStatus.ACTIVE,
  parentId: "sun",
  realMass_kg: 6.4171e23,
  realRadius_m: kmToM(3389.5),
  temperature: 209,
  albedo: 0.25,
  orbit: createOrbitalElements({
    semiMajorAxisAU: 1.52368055,
    eccentricity: 0.0934,
    inclinationDeg: 1.85,
    longitudeOfAscendingNodeDeg: 49.57854,
    argumentOfPeriapsisDeg: 286.5,
    meanAnomalyDeg: 19.412,
    period_s: 5.935e7,
    siderealRotationPeriod_s: 8.864e4,
    axialTiltDeg: 25.19,
    epoch: J2000_EPOCH,
  }),
  properties: {
    type: CelestialType.PLANET,
    classType: PlanetType.TERRESTRIAL,
    isMoon: false,
    composition: [
      "silicates",
      "iron oxide",
      "thin CO2 atmosphere",
      "water ice caps",
    ],
    atmosphere: {
      glowColor: "#FF6B35",
      intensity: 0.3,
      power: 1.5,
      thickness: 0.15,
    },
    surface: {
      roughness: 0.8,
      persistence: 0.65,
      lacunarity: 2.1,
      simplePeriod: 3.2,
      octaves: 9,
      bumpScale: 2.8,
      color1: "#3A2C2C",
      color2: "#A13030",
      color3: "#401717",
      color4: "#A72711",
      color5: "#621D1D",
      height1: 0.1,
      height2: 0.25,
      height3: 0.45,
      height4: 0.7,
      height5: 0.9,
      shininess: 10,
      specularStrength: 0.25,
      ambientLightIntensity: 0.01,
      undulation: 0.6,
      terrainType: 3,
      terrainAmplitude: 0.8,
      terrainSharpness: 1.4,
      terrainOffset: 0.1,
    },
  },
};
