import {
  createOrbitalElements,
  J2000_EPOCH,
  kmToM,
} from "@teskooano/core-physics";
import {
  CelestialType,
  PlanetType,
  CelestialStatus,
  type CelestialObject,
  type PlanetProperties,
} from "@teskooano/data-types";

/**
 * Phobos moon configuration object for modular solar system initialization.
 */
export const phobos: CelestialObject<PlanetProperties> = {
  id: "phobos",
  name: "Phobos",
  seed: "phobos_fear_mars_moon",
  type: CelestialType.MOON,
  status: CelestialStatus.ACTIVE,
  parentId: "mars",
  realMass_kg: 1.06e16,
  realRadius_m: kmToM(11.08),
  temperature: 233,
  albedo: 0.071,
  orbit: createOrbitalElements({
    semiMajorAxisAU: 0.000062,
    eccentricity: 0.0151,
    inclinationDeg: 1.093,
    longitudeOfAscendingNodeDeg: 169.2,
    argumentOfPeriapsisDeg: 216.3,
    meanAnomalyDeg: 189.7,
    period_s: 0.31891023 * 24 * 3600,
    siderealRotationPeriod_s: 0.31891023 * 24 * 3600,
    axialTiltDeg: 0,
    epoch: J2000_EPOCH,
  }),
  properties: {
    type: CelestialType.MOON,
    classType: PlanetType.ROCKY,
    isMoon: true,
    composition: [
      "carbonaceous chondrite",
      "C-type rock",
      "meteoroid impact debris",
      "fine dust regolith",
    ],
    shapeModel: "asteroid",
    atmosphere: undefined,
    surface: {
      roughness: 0.9,
      persistence: 0.4,
      lacunarity: 2.0,
      simplePeriod: 3.0,
      octaves: 5,
      bumpScale: 0.2,
      color1: "#404040",
      color2: "#505050",
      color3: "#606060",
      color4: "#707070",
      color5: "#808080",
      height1: 0.0,
      height2: 0.25,
      height3: 0.5,
      height4: 0.75,
      height5: 1.0,
      shininess: 0.01,
      specularStrength: 0.01,
      ambientLightIntensity: 0.01,
      undulation: 0.3,
      terrainType: 1,
      terrainAmplitude: 0.5,
      terrainSharpness: 0.8,
      terrainOffset: 0.0,
    },
  },
};
