import {
  createOrbitalElements,
  J2000_EPOCH,
  kmToM,
} from "@teskooano/core-physics";
import {
  CelestialStatus,
  CelestialType,
  PlanetType,
  type CelestialObject,
  type PlanetProperties,
} from "@teskooano/data-types";

/**
 * Callisto moon configuration object for modular solar system initialization.
 */
export const callisto: CelestialObject<PlanetProperties> = {
  id: "callisto",
  name: "Callisto",
  seed: "callisto_seed_16689",
  type: CelestialType.MOON,
  status: CelestialStatus.ACTIVE,
  parentId: "jupiter",
  realMass_kg: 1.075938e23,
  realRadius_m: kmToM(2410.3),
  temperature: 134,
  albedo: 0.22,
  orbit: createOrbitalElements({
    semiMajorAxisAU: 0.0126,
    eccentricity: 0.0074,
    inclinationDeg: 0.192,
    longitudeOfAscendingNodeDeg: 298.848,
    argumentOfPeriapsisDeg: 52.643,
    meanAnomalyDeg: 181.408,
    period_s: 16.6890184 * 24 * 3600,
    siderealRotationPeriod_s: 16.6890184 * 24 * 3600,
    axialTiltDeg: 0,
    epoch: J2000_EPOCH,
  }),
  properties: {
    type: CelestialType.MOON,
    classType: PlanetType.BARREN,
    isMoon: true,
    composition: [
      "water ice",
      "rocky material",
      "subsurface ocean",
      "undifferentiated interior",
      "carbonaceous material",
    ],
    atmosphere: {
      glowColor: "#E0E0E0",
      intensity: 0.02,
      power: 0.5,
      thickness: 0.01,
    },
    surface: {
      roughness: 0.8,
      persistence: 0.6,
      lacunarity: 2.4,
      simplePeriod: 3.0,
      octaves: 11,
      bumpScale: 3.2,
      color1: "#404050",
      color2: "#505060",
      color3: "#606070",
      color4: "#707080",
      color5: "#808090",
      height1: 0.05,
      height2: 0.2,
      height3: 0.4,
      height4: 0.65,
      height5: 0.85,
      shininess: 6,
      specularStrength: 0.05,
      ambientLightIntensity: 0.01,
      undulation: 0.35,
      terrainType: 2,
      terrainAmplitude: 1.1,
      terrainSharpness: 2.0,
      terrainOffset: -0.15,
    },
  },
};
