import { createOrbitalElements, kmToM } from "@teskooano/core-physics";
import {
  CelestialStatus,
  CelestialType,
  PlanetType,
  type CelestialObject,
  type PlanetProperties,
} from "@teskooano/data-types";
import { J2000_EPOCH } from "@teskooano/data-values";

/**
 * Europa moon configuration object for modular solar system initialization.
 */
export const europa: CelestialObject<PlanetProperties> = {
  id: "europa",
  name: "Europa",
  seed: "europa_seed_3551",
  type: CelestialType.MOON,
  status: CelestialStatus.ACTIVE,
  parentId: "jupiter",
  realMass_kg: 4.799844e22,
  realRadius_m: kmToM(1560.8),
  temperature: 102,
  albedo: 0.67,
  orbit: createOrbitalElements({
    semiMajorAxisAU: 0.00449,
    eccentricity: 0.009,
    inclinationDeg: 0.47,
    longitudeOfAscendingNodeDeg: 219.106,
    argumentOfPeriapsisDeg: 88.97,
    meanAnomalyDeg: 171.016,
    period_s: 3.551181 * 24 * 3600,
    siderealRotationPeriod_s: 3.551181 * 24 * 3600,
    axialTiltDeg: 0,
    epoch: J2000_EPOCH,
  }),
  properties: {
    type: CelestialType.MOON,
    classType: PlanetType.BARREN,
    isMoon: true,
    composition: [
      "water ice shell",
      "silicate mantle",
      "iron core",
      "subsurface ocean",
    ],
    atmosphere: {
      glowColor: "#FFFFFF",
      intensity: 0.02,
      power: 0.5,
      thickness: 0.01,
    },
    surface: {
      roughness: 0.3,
      persistence: 0.53,
      lacunarity: 2.15,
      simplePeriod: 0.86,
      octaves: 8,
      bumpScale: 10,
      color1: "#E8F4F8",
      color2: "#F0F4F8",
      color3: "#F8F8F8",
      color4: "#FFFFFF",
      color5: "#F0FFFF",
      height1: 0.088,
      height2: 0.41,
      height3: 0.4,
      height4: 0.43,
      height5: 0.43,
      shininess: 40,
      specularStrength: 0.35,
      ambientLightIntensity: 0.01,
      undulation: 0.1,
      terrainType: 3,
      terrainAmplitude: 0.19,
      terrainSharpness: 1.3,
      terrainOffset: 0.25,
    },
  },
};
