import { createOrbitalElements, kmToM } from "@teskooano/core-physics";
import {
  CelestialStatus,
  CelestialType,
  PlanetType,
  type CelestialObject,
  type PlanetProperties,
} from "@teskooano/data-types";
import { J2000_EPOCH } from "@teskooano/data-values";

/**
 * Ganymede moon configuration object for modular solar system initialization.
 */
export const ganymede: CelestialObject<PlanetProperties> = {
  id: "ganymede",
  name: "Ganymede",
  seed: "ganymede_seed_7155",
  type: CelestialType.MOON,
  status: CelestialStatus.ACTIVE,
  parentId: "jupiter",
  realMass_kg: 1.4819e23,
  realRadius_m: kmToM(2634.1),
  temperature: 110,
  albedo: 0.43,
  orbit: createOrbitalElements({
    semiMajorAxisAU: 0.00715,
    eccentricity: 0.0013,
    inclinationDeg: 0.2,
    longitudeOfAscendingNodeDeg: 63.552,
    argumentOfPeriapsisDeg: 192.417,
    meanAnomalyDeg: 317.54,
    period_s: 7.15455296 * 24 * 3600,
    siderealRotationPeriod_s: 7.15455296 * 24 * 3600,
    axialTiltDeg: 0,
    epoch: J2000_EPOCH,
  }),
  properties: {
    type: CelestialType.MOON,
    classType: PlanetType.BARREN,
    isMoon: true,
    composition: [
      "water ice",
      "silicates",
      "iron-rich core",
      "subsurface ocean",
    ],
    atmosphere: {
      glowColor: "#FFFFFF",
      intensity: 0.01,
      power: 0.4,
      thickness: 0.005,
    },
    surface: {
      roughness: 0.4,
      persistence: 0.5,
      lacunarity: 2.0,
      simplePeriod: 2.5,
      octaves: 9,
      bumpScale: 2.7,
      color1: "#A0A8B0",
      color2: "#C0C8D0",
      color3: "#D0D8E0",
      color4: "#E0E8F0",
      color5: "#F0F8FF",
      height1: 0.1,
      height2: 0.3,
      height3: 0.5,
      height4: 0.7,
      height5: 0.9,
      shininess: 25,
      specularStrength: 0.2,
      ambientLightIntensity: 0.01,
      undulation: 0.2,
      terrainType: 2,
      terrainAmplitude: 0.75,
      terrainSharpness: 1.2,
      terrainOffset: 0.05,
    },
  },
};
