import {
  createOrbitalElements,
  J2000_EPOCH,
  kmToM,
} from "@teskooano/core-physics";
import {
  CelestialType,
  PlanetType,
  CelestialStatus,
  type CelestialObject,
  type PlanetProperties,
} from "@teskooano/data-types";

/**
 * Himalia moon configuration object for modular solar system initialization.
 */
export const himalia: CelestialObject<PlanetProperties> = {
  id: "himalia",
  name: "Himalia",
  seed: "himalia_seed_1904",
  type: CelestialType.MOON,
  status: CelestialStatus.ACTIVE,
  parentId: "jupiter",
  realMass_kg: 6.74e18,
  realRadius_m: kmToM(85),
  temperature: 124,
  albedo: 0.04,
  orbit: createOrbitalElements({
    semiMajorAxisAU: 0.0764,
    eccentricity: 0.16,
    inclinationDeg: 28.4,
    longitudeOfAscendingNodeDeg: 64.2,
    argumentOfPeriapsisDeg: 321.1,
    meanAnomalyDeg: 78.3,
    period_s: 249.909 * 24 * 3600,
    siderealRotationPeriod_s: 0.324 * 24 * 3600,
    axialTiltDeg: 0,
    epoch: J2000_EPOCH,
  }),
  properties: {
    type: CelestialType.MOON,
    classType: PlanetType.ROCKY,
    isMoon: true,
    composition: ["rock", "ice"],
    surface: {
      roughness: 0.9,
      persistence: 0.5,
      lacunarity: 2.1,
      simplePeriod: 2.5,
      octaves: 7,
      bumpScale: 0.8,
      color1: "#616161",
      color2: "#757575",
      color3: "#9E9E9E",
      color4: "#BDBDBD",
      color5: "#E0E0E0",
      height1: 0.1,
      height2: 0.3,
      height3: 0.5,
      height4: 0.7,
      height5: 0.9,
      shininess: 3,
      specularStrength: 0.05,
      ambientLightIntensity: 0.01,
      undulation: 0.2,
      terrainType: 1,
      terrainAmplitude: 0.3,
      terrainSharpness: 1.8,
      terrainOffset: 0.1,
    },
  },
};
