import {
  createOrbitalElements,
  J2000_EPOCH,
  kmToM,
} from "@teskooano/core-physics";
import {
  CelestialType,
  PlanetType,
  CelestialStatus,
  type CelestialObject,
  type PlanetProperties,
} from "@teskooano/data-types";

/**
 * Io moon configuration object for modular solar system initialization.
 */
export const io: CelestialObject<PlanetProperties> = {
  id: "io",
  name: "Io",
  seed: "io_seed_1769",
  type: CelestialType.MOON,
  status: CelestialStatus.ACTIVE,
  parentId: "jupiter",
  realMass_kg: 8.9319e22,
  realRadius_m: kmToM(1821.6),
  temperature: 110,
  albedo: 0.63,
  orbit: createOrbitalElements({
    semiMajorAxisAU: 0.00283,
    eccentricity: 0.0041,
    inclinationDeg: 0.05,
    longitudeOfAscendingNodeDeg: 43.977,
    argumentOfPeriapsisDeg: 84.129,
    meanAnomalyDeg: 342.021,
    period_s: 1.769137786 * 24 * 3600,
    siderealRotationPeriod_s: 1.769137786 * 24 * 3600,
    axialTiltDeg: 0,
    epoch: J2000_EPOCH,
  }),
  properties: {
    type: CelestialType.MOON,
    classType: PlanetType.ROCKY,
    isMoon: true,
    composition: [
      "sulfur compounds",
      "silicates",
      "iron core",
      "molten interior",
    ],
    atmosphere: {
      glowColor: "#FFFF00",
      intensity: 0.1,
      power: 0.8,
      thickness: 0.05,
    },
    surface: {
      roughness: 0.6,
      persistence: 0.58,
      lacunarity: 1.9,
      simplePeriod: 1.7,
      octaves: 8,
      bumpScale: 2.5,
      color1: "#FFFFA0",
      color2: "#FF6347",
      color3: "#FF2000",
      color4: "#8B4513",
      color5: "#201000",
      height1: 0.15,
      height2: 0.35,
      height3: 0.55,
      height4: 0.75,
      height5: 0.9,
      shininess: 18,
      specularStrength: 0.3,
      ambientLightIntensity: 0.01,
      undulation: 0.4,
      terrainType: 2,
      terrainAmplitude: 1.2,
      terrainSharpness: 1.8,
      terrainOffset: 0.2,
    },
  },
};
