import { createOrbitalElements, kmToM } from "@teskooano/core-physics";
import {
  CelestialType,
  PlanetType,
  CelestialStatus,
  type PlanetProperties,
  CelestialObject,
} from "@teskooano/data-types";

/**
 * Titan configuration object for modular solar system initialization.
 */
export const titan: CelestialObject<PlanetProperties> = {
  id: "titan",
  name: "Titan",
  seed: "titan_seed_15945",
  type: CelestialType.MOON,
  status: CelestialStatus.ACTIVE,
  parentId: "saturn",
  realMass_kg: 1.34518e23,
  realRadius_m: kmToM(2574.73),
  temperature: 93.7,
  albedo: 0.22,
  orbit: createOrbitalElements({
    semiMajorAxisAU: 0.0081652,
    eccentricity: 0.0288,
    inclinationDeg: 0.34854,
    longitudeOfAscendingNodeDeg: 189.64,
    argumentOfPeriapsisDeg: 180.532,
    meanAnomalyDeg: 358.922,
    period_s: 15.945 * 24 * 3600,
    siderealRotationPeriod_s: 15.945 * 24 * 3600,
    axialTiltDeg: 0,
  }),
  properties: {
    type: CelestialType.MOON,
    classType: PlanetType.TERRESTRIAL,
    isMoon: true,
    composition: [
      "water ice",
      "rocky material",
      "organic compounds",
      "nitrogen atmosphere",
      "methane lakes",
      "subsurface ocean",
    ],
    atmosphere: {
      glowColor: "#FFA500",
      intensity: 1.0,
      power: 20.0,
      thickness: 1.0,
      opacity: 1.0,
    },
    surface: {
      roughness: 0.6,
      persistence: 0.7,
      lacunarity: 2.0,
      simplePeriod: 4.0,
      octaves: 8,
      bumpScale: 2.5,
      color1: "#8B4513",
      color2: "#A0522D",
      color3: "#CD853F",
      color4: "#DEB887",
      color5: "#F5DEB3",
      height1: 0.1,
      height2: 0.3,
      height3: 0.5,
      height4: 0.7,
      height5: 0.9,
      shininess: 8,
      specularStrength: 0.05,
      ambientLightIntensity: 0.01,
      undulation: 0.25,
      terrainType: 3,
      terrainAmplitude: 0.8,
      terrainSharpness: 1.5,
      terrainOffset: 0.1,
    },
  },
};
