import { createOrbitalElements, kmToM } from "@teskooano/core-physics";
import {
  type CelestialObject,
  CelestialType,
  CelestialStatus,
  PlanetType,
  type PlanetProperties,
} from "@teskooano/data-types";

/**
 * Naiad configuration object for modular solar system initialization.
 */
export const naiad: CelestialObject<PlanetProperties> = {
  id: "naiad",
  name: "Naiad",
  seed: "naiad",
  type: CelestialType.MOON,
  status: CelestialStatus.ACTIVE,
  parentId: "neptune",
  realMass_kg: 4e17,
  realRadius_m: 33000,
  temperature: 60,
  albedo: 0.07,
  orbit: createOrbitalElements({
    semiMajorAxisAU: 0.00032,
    eccentricity: 0.0047,
    inclinationDeg: 4.75,
    longitudeOfAscendingNodeDeg: 0,
    argumentOfPeriapsisDeg: 0,
    meanAnomalyDeg: 0,
    period_s: 7.057 * 3600,
    siderealRotationPeriod_s: 7.057 * 3600,
    axialTiltDeg: 0,
  }),
  properties: {
    type: CelestialType.MOON,
    classType: PlanetType.ROCKY,
    isMoon: true,
    composition: ["water ice", "rock"],
    surface: {
      roughness: 0.8,
      persistence: 0.5,
      lacunarity: 2.1,
      simplePeriod: 3.0,
      octaves: 6,
      bumpScale: 0.6,
      color1: "#6A6A6A",
      color2: "#8A8A8A",
      color3: "#A0A0A0",
      color4: "#B8B8B8",
      color5: "#D0D0D0",
      height1: 0.05,
      height2: 0.25,
      height3: 0.5,
      height4: 0.75,
      height5: 0.9,
      shininess: 4,
      specularStrength: 0.08,
      ambientLightIntensity: 0.01,
      undulation: 0.2,
      terrainType: 1,
      terrainAmplitude: 0.3,
      terrainSharpness: 1.4,
      terrainOffset: 0.0,
    },
  },
};
