import { createOrbitalElements, kmToM } from "@teskooano/core-physics";
import {
  type CelestialObject,
  CelestialType,
  CelestialStatus,
  PlanetType,
  type PlanetProperties,
} from "@teskooano/data-types";

export const triton: CelestialObject<PlanetProperties> = {
  id: "triton",
  name: "Triton",
  seed: "triton_seed_5877",
  type: CelestialType.MOON,
  status: CelestialStatus.ACTIVE,
  parentId: "neptune",
  realMass_kg: 2.139e22,
  realRadius_m: kmToM(1353.4),
  temperature: 38,
  albedo: 0.76,
  orbit: createOrbitalElements({
    semiMajorAxisAU: 0.002371, // Approximately 354,800 km (real value)
    eccentricity: 0.000016,
    inclinationDeg: 156.885,
    longitudeOfAscendingNodeDeg: 249.7,
    argumentOfPeriapsisDeg: 275.1,
    meanAnomalyDeg: 296.6,
    period_s: 5.877 * 24 * 3600,
    siderealRotationPeriod_s: 5.877 * 24 * 3600,
    axialTiltDeg: 0,
  }),
  properties: {
    type: CelestialType.MOON,
    classType: PlanetType.BARREN,
    isMoon: true,
    composition: ["nitrogen ice", "water ice", "methane ice", "rocky core"],
    surface: {
      roughness: 0.5,
      persistence: 0.53,
      lacunarity: 2.14,
      simplePeriod: 0.87,
      octaves: 8,
      bumpScale: 10,
      color1: "#B0C0D0",
      color2: "#D0E0F0",
      color3: "#E0F0F0",
      color4: "#F0F8FF",
      color5: "#FFFFFF",
      height1: 0.088,
      height2: 0.41,
      height3: 0.4,
      height4: 0.43,
      height5: 0.43,
      shininess: 23,
      specularStrength: 0.47,
      ambientLightIntensity: 0.01,
      undulation: 0.1,
      terrainType: 3,
      terrainAmplitude: 0.2,
      terrainSharpness: 1.3,
      terrainOffset: 0.25,
    },
  },
};
