/**
 * TextureBasedPlanetMaterial - Material using pre-generated texture maps.
 *
 * Uses textures from the TerrainTextureGenerator instead of real-time
 * procedural generation. This provides better visual quality for
 * complex terrain features like craters and erosion.
 *
 * @module materials/texture-based-planet.material
 */

import * as THREE from "three";
import type { GeneratedPlanetTextures } from "../texture-generation/types";

// Import shaders
import vertexShader from "../texture-generation/shaders/texture-based-planet.vert.glsl";
import fragmentShader from "../texture-generation/shaders/texture-based-planet.frag.glsl";

/**
 * Maximum number of shadow casters (must match shader constant).
 */
const MAX_SHADOW_CASTERS = 4;

/**
 * Configuration options for TextureBasedPlanetMaterial.
 */
export interface TextureBasedPlanetMaterialOptions {
  /** Generated planet textures */
  textures: GeneratedPlanetTextures;
  /** Vertex displacement scale (default: 0.02) */
  displacementScale?: number;
  /** Metalness value (default: 0.0) */
  metalness?: number;
  /** Ambient light color */
  ambientColor?: THREE.Color;
  /** Ambient light intensity */
  ambientIntensity?: number;
}

/**
 * Shadow caster data for the material.
 */
export interface ShadowCasterData {
  position: THREE.Vector3;
  radius: number;
}

/**
 * TextureBasedPlanetMaterial renders planets using pre-generated textures.
 *
 * This material is used when textures have been generated by the
 * TerrainTextureGenerator, providing better visual quality for
 * features like craters and erosion that are difficult to compute
 * in real-time.
 */
export class TextureBasedPlanetMaterial extends THREE.ShaderMaterial {
  /**
   * Creates a new TextureBasedPlanetMaterial.
   *
   * @param options - Material configuration options
   */
  constructor(options: TextureBasedPlanetMaterialOptions) {
    const {
      textures,
      displacementScale = 0.02,
      metalness = 0.0,
      ambientColor = new THREE.Color(0.1, 0.1, 0.15),
      ambientIntensity = 0.02,
    } = options;

    // Initialize shadow caster uniforms
    const shadowCasterPositions: THREE.Vector3[] = [];
    const shadowCasterRadii: number[] = [];
    for (let i = 0; i < MAX_SHADOW_CASTERS; i++) {
      shadowCasterPositions.push(new THREE.Vector3());
      shadowCasterRadii.push(0);
    }

    super({
      vertexShader,
      fragmentShader,
      uniforms: THREE.UniformsUtils.merge([
        THREE.UniformsLib.lights,
        {
          // Texture maps
          uHeightMap: { value: textures.heightMap },
          uColorMap: { value: textures.colorMap },
          uNormalMap: { value: textures.normalMap },
          uRoughnessMap: { value: textures.roughnessMap },

          // Material properties
          uDisplacementScale: { value: displacementScale },
          uMetalness: { value: metalness },

          // Ambient lighting
          uAmbientColor: { value: ambientColor },
          uAmbientIntensity: { value: ambientIntensity },

          // Shadow casters
          uNumShadowCasters: { value: 0 },
          uShadowCasters: {
            value: shadowCasterPositions.map((pos, i) => ({
              position: pos,
              radius: shadowCasterRadii[i],
            })),
          },
        },
      ]),
      lights: true,
      defines: {
        MAX_SHADOW_CASTERS: MAX_SHADOW_CASTERS,
      },
    });

    // Store textures reference for disposal
    this.userData.textures = textures;
  }

  /**
   * Updates shadow caster data.
   *
   * @param shadowCasters - Array of shadow caster data
   */
  updateShadowCasters(shadowCasters: ShadowCasterData[]): void {
    const count = Math.min(shadowCasters.length, MAX_SHADOW_CASTERS);
    this.uniforms.uNumShadowCasters.value = count;

    const casterArray = this.uniforms.uShadowCasters.value as Array<{
      position: THREE.Vector3;
      radius: number;
    }>;

    for (let i = 0; i < MAX_SHADOW_CASTERS; i++) {
      if (i < count) {
        casterArray[i].position.copy(shadowCasters[i].position);
        casterArray[i].radius = shadowCasters[i].radius;
      } else {
        casterArray[i].position.set(0, 0, 0);
        casterArray[i].radius = 0;
      }
    }
  }

  /**
   * Updates ambient lighting.
   *
   * @param color - Ambient color
   * @param intensity - Ambient intensity
   */
  updateAmbientLight(color: THREE.Color, intensity: number): void {
    this.uniforms.uAmbientColor.value.copy(color);
    this.uniforms.uAmbientIntensity.value = intensity;
  }

  /**
   * Updates displacement scale.
   *
   * @param scale - New displacement scale
   */
  setDisplacementScale(scale: number): void {
    this.uniforms.uDisplacementScale.value = scale;
  }

  /**
   * Disposes of the material and its textures.
   */
  dispose(): void {
    super.dispose();

    // Dispose textures if they were stored
    const textures = this.userData.textures as
      | GeneratedPlanetTextures
      | undefined;
    if (textures) {
      textures.dispose();
    }
  }
}
