// Type definitions for virtual:teskooano-loaders

// This module is generated by the teskooanoUiPlugin Vite plugin.
declare module 'virtual:teskooano-loaders' {
  /**
   * An object mapping component tag names to asynchronous functions
   * that return the module containing the component class (usually as default export).
   */
  export const componentLoaders: Record<string, () => Promise<any>>;

  /**
   * An object mapping plugin IDs to asynchronous functions that return
   * the module containing the TeskooanoPlugin object (usually exported as 'plugin').
   */
  export const pluginLoaders: Record<string, () => Promise<any>>;
} 