import { DEG_TO_RAD, OSVector3 } from "@teskooano/core-math";
import { KM } from "@teskooano/core-physics";
import { actions } from "@teskooano/core-state";
import {
  AtmosphereType,
  CelestialType,
  PlanetType,
  SurfaceType,
  type PlanetProperties,
  type ProceduralSurfaceProperties,
} from "@teskooano/data-types";

const IO_MASS_KG = 8.9319e22;
const IO_RADIUS_M = 1821600;
const IO_SMA_M = 421700 * KM;
const IO_ECC = 0.0041;
const IO_INC_DEG = 0.05;
const IO_SIDEREAL_PERIOD_S = 152854;
const IO_ALBEDO = 0.63;

const EUROPA_MASS_KG = 4.7998e22;
const EUROPA_RADIUS_M = 1560800;
const EUROPA_SMA_M = 671034 * KM;
const EUROPA_ECC = 0.0094;
const EUROPA_INC_DEG = 0.471;
const EUROPA_SIDEREAL_PERIOD_S = 306822;
const EUROPA_ALBEDO = 0.67;

const GANYMEDE_MASS_KG = 1.4819e23;
const GANYMEDE_RADIUS_M = 2631200;
const GANYMEDE_SMA_M = 1070412 * KM;
const GANYMEDE_ECC = 0.0013;
const GANYMEDE_INC_DEG = 0.204;
const GANYMEDE_SIDEREAL_PERIOD_S = 618153;
const GANYMEDE_ALBEDO = 0.43;

const CALLISTO_MASS_KG = 1.0759e23;
const CALLISTO_RADIUS_M = 2410300;
const CALLISTO_SMA_M = 1882709 * KM;
const CALLISTO_ECC = 0.0074;
const CALLISTO_INC_DEG = 0.205;
const CALLISTO_SIDEREAL_PERIOD_S = 1441902;
const CALLISTO_ALBEDO = 0.17;

/**
 * Initializes Jupiter's moons.
 * @param jupiterId The ID of Jupiter.
 */
export function initializeJupiterMoons(jupiterId: string): void {
  const defaultMoonAxialTilt = new OSVector3(0, 1, 0);

  // Io
  const ioProceduralSurface: ProceduralSurfaceProperties = {
    persistence: 0.6,
    lacunarity: 2.3,
    simplePeriod: 4.0,
    octaves: 7,
    bumpScale: 0.4,
    color1: "#201000",
    color2: "#8B4513",
    color3: "#CD853F",
    color4: "#FFFFA0",
    color5: "#FF2000",
    height1: 0.0,
    height2: 0.2,
    height3: 0.5,
    height4: 0.8,
    height5: 0.95,
    shininess: 0.1,
    specularStrength: 0.2,
    roughness: 0.6,
    ambientLightIntensity: 0.15,
    undulation: 0.3,
    terrainType: 2,
    terrainAmplitude: 0.5,
    terrainSharpness: 0.8,
    terrainOffset: 0.1,
  };
  actions.addCelestial({
    id: "io",
    name: "Io",
    seed: "io_seed_1769",
    type: CelestialType.MOON,
    parentId: jupiterId,
    realMass_kg: IO_MASS_KG,
    realRadius_m: IO_RADIUS_M,
    temperature: 110,
    albedo: IO_ALBEDO,
    siderealRotationPeriod_s: IO_SIDEREAL_PERIOD_S,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: IO_SMA_M,
      eccentricity: IO_ECC,
      inclination: IO_INC_DEG * DEG_TO_RAD,
      longitudeOfAscendingNode: Math.random() * 2 * Math.PI,
      argumentOfPeriapsis: Math.random() * 2 * Math.PI,
      meanAnomaly: Math.random() * 2 * Math.PI,
      period_s: IO_SIDEREAL_PERIOD_S,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ROCKY_WORLD,
      isMoon: true,
      parentPlanet: jupiterId,
      composition: ["silicate rock", "sulfur compounds"],
      atmosphere: {
        type: AtmosphereType.THIN,
        composition: ["sulfur dioxide"],
        pressure_pa: 1e-7,
        density_kgm3: 1e-9,
        scaleHeight_m: 100000,
        glowColor: "#FFFFE0",
        intensity: 0.1,
        power: 1.0,
        thickness: 0.05,
      },
      surface: {
        surfaceType: SurfaceType.VOLCANIC,

        proceduralData: {
          ...ioProceduralSurface,
          planetType: PlanetType.LAVA_WORLD,
        },
      },
    } as PlanetProperties,
  });

  // Europa
  const europaProceduralSurface: ProceduralSurfaceProperties = {
    persistence: 0.4,
    lacunarity: 2.0,
    simplePeriod: 8.0,
    octaves: 6,
    bumpScale: 0.1,
    color1: "#E0F0FF",
    color2: "#F0F8FF",
    color3: "#FFFFFF",
    color4: "#F8F8FF",
    color5: "#FFFAFA",
    height1: 0.0,
    height2: 0.4,
    height3: 0.6,
    height4: 0.8,
    height5: 1.0,
    shininess: 0.8,
    specularStrength: 0.7,
    roughness: 0.3,
    ambientLightIntensity: 0.2,
    undulation: 0.05,
    terrainType: 1,
    terrainAmplitude: 0.1,
    terrainSharpness: 0.4,
    terrainOffset: 0.0,
  };
  actions.addCelestial({
    id: "europa",
    name: "Europa",
    seed: "europa_seed_3551",
    type: CelestialType.MOON,
    parentId: jupiterId,
    realMass_kg: EUROPA_MASS_KG,
    realRadius_m: EUROPA_RADIUS_M,
    temperature: 102,
    albedo: EUROPA_ALBEDO,
    siderealRotationPeriod_s: EUROPA_SIDEREAL_PERIOD_S,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: EUROPA_SMA_M,
      eccentricity: EUROPA_ECC,
      inclination: EUROPA_INC_DEG * DEG_TO_RAD,
      longitudeOfAscendingNode: Math.random() * 2 * Math.PI,
      argumentOfPeriapsis: Math.random() * 2 * Math.PI,
      meanAnomaly: Math.random() * 2 * Math.PI,
      period_s: EUROPA_SIDEREAL_PERIOD_S,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ICE_WORLD,
      isMoon: true,
      parentPlanet: jupiterId,
      composition: [
        "water ice shell",
        "silicate rock core",
        "possible subsurface ocean",
      ],
      atmosphere: {
        type: AtmosphereType.THIN,
        composition: ["oxygen"],
        pressure_pa: 1e-7,
        density_kgm3: 1e-9,
        scaleHeight_m: 100000,
        glowColor: "#ADD8E6",
        intensity: 0.05,
        power: 1.0,
        thickness: 0.02,
      },
      surface: {
        surfaceType: SurfaceType.ICE_CRACKED,
        proceduralData: {
          ...europaProceduralSurface,
          planetType: PlanetType.ICE_WORLD,
        },
      },
    } as PlanetProperties,
  });

  // Ganymede
  const ganymedeProceduralSurface: ProceduralSurfaceProperties = {
    persistence: 0.5,
    lacunarity: 2.1,
    simplePeriod: 6.0,
    octaves: 7,
    bumpScale: 0.2,
    color1: "#666666",
    color2: "#888888",
    color3: "#AAAAAA",
    color4: "#C0C0C0",
    color5: "#E0E0E0",
    height1: 0.0,
    height2: 0.3,
    height3: 0.5,
    height4: 0.7,
    height5: 0.9,
    shininess: 0.4,
    specularStrength: 0.3,
    roughness: 0.5,
    ambientLightIntensity: 0.1,
    undulation: 0.1,
    terrainType: 1,
    terrainAmplitude: 0.2,
    terrainSharpness: 0.6,
    terrainOffset: 0.0,
  };
  actions.addCelestial({
    id: "ganymede",
    name: "Ganymede",
    seed: "ganymede_seed_7155",
    type: CelestialType.MOON,
    parentId: jupiterId,
    realMass_kg: GANYMEDE_MASS_KG,
    realRadius_m: GANYMEDE_RADIUS_M,
    temperature: 110,
    albedo: GANYMEDE_ALBEDO,
    siderealRotationPeriod_s: GANYMEDE_SIDEREAL_PERIOD_S,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: GANYMEDE_SMA_M,
      eccentricity: GANYMEDE_ECC,
      inclination: GANYMEDE_INC_DEG * DEG_TO_RAD,
      longitudeOfAscendingNode: Math.random() * 2 * Math.PI,
      argumentOfPeriapsis: Math.random() * 2 * Math.PI,
      meanAnomaly: Math.random() * 2 * Math.PI,
      period_s: GANYMEDE_SIDEREAL_PERIOD_S,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ICE_WORLD,
      isMoon: true,
      parentPlanet: jupiterId,
      composition: ["water ice", "silicate rock"],
      atmosphere: {
        type: AtmosphereType.THIN,
        composition: ["oxygen"],
        pressure_pa: 1e-7,
        density_kgm3: 1e-9,
        scaleHeight_m: 100000,
        glowColor: "#E0E0E0",
        intensity: 0.05,
        power: 1.0,
        thickness: 0.02,
      },
      surface: {
        surfaceType: SurfaceType.VARIED,
        proceduralData: {
          ...ganymedeProceduralSurface,
          planetType: PlanetType.ICE_WORLD,
        },
      },
    } as PlanetProperties,
  });

  // Callisto
  const callistoProceduralSurface: ProceduralSurfaceProperties = {
    persistence: 0.45,
    lacunarity: 2.0,
    simplePeriod: 5.0,
    octaves: 6,
    bumpScale: 0.25,
    color1: "#1A1A1A",
    color2: "#2A2A2A",
    color3: "#3A3A3A",
    color4: "#4A4A4A",
    color5: "#5A5A5A",
    height1: 0.0,
    height2: 0.25,
    height3: 0.5,
    height4: 0.75,
    height5: 0.9,
    shininess: 0.05,
    specularStrength: 0.05,
    roughness: 0.7,
    ambientLightIntensity: 0.05,
    undulation: 0.15,
    terrainType: 1,
    terrainAmplitude: 0.3,
    terrainSharpness: 0.7,
    terrainOffset: 0.0,
  };
  actions.addCelestial({
    id: "callisto",
    name: "Callisto",
    seed: "callisto_seed_16690",
    type: CelestialType.MOON,
    parentId: jupiterId,
    realMass_kg: CALLISTO_MASS_KG,
    realRadius_m: CALLISTO_RADIUS_M,
    temperature: 134,
    albedo: CALLISTO_ALBEDO,
    siderealRotationPeriod_s: CALLISTO_SIDEREAL_PERIOD_S,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: CALLISTO_SMA_M,
      eccentricity: CALLISTO_ECC,
      inclination: CALLISTO_INC_DEG * DEG_TO_RAD,
      longitudeOfAscendingNode: Math.random() * 2 * Math.PI,
      argumentOfPeriapsis: Math.random() * 2 * Math.PI,
      meanAnomaly: Math.random() * 2 * Math.PI,
      period_s: CALLISTO_SIDEREAL_PERIOD_S,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ICE_WORLD,
      isMoon: true,
      parentPlanet: jupiterId,
      composition: ["ice and rock"],
      atmosphere: {
        type: AtmosphereType.THIN,
        composition: ["carbon dioxide"],
        pressure_pa: 7.5e-7,
        density_kgm3: 1e-9,
        scaleHeight_m: 100000,
        glowColor: "#A9A9A9",
        intensity: 0.03,
        power: 1.0,
        thickness: 0.01,
      },
      surface: {
        surfaceType: SurfaceType.CRATERED,
        proceduralData: {
          ...callistoProceduralSurface,
          planetType: PlanetType.ICE_WORLD,
        },
      },
    } as PlanetProperties,
  });

  // Amalthea
  actions.addCelestial({
    id: "amalthea",
    parentId: jupiterId,
    name: "Amalthea",
    type: CelestialType.MOON,
    realMass_kg: 2.08e18,
    realRadius_m: 83.5 * KM,
    temperature: 120,
    albedo: 0.05,
    siderealRotationPeriod_s: 0.498 * 24 * 60 * 60,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 181366 * KM,
      eccentricity: 0.003,
      inclination: 0.374 * DEG_TO_RAD,
      meanAnomaly: 0,
      argumentOfPeriapsis: 0,
      longitudeOfAscendingNode: 0,
      period_s: 0.498 * 24 * 60 * 60,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ROCKY_WORLD,
      isMoon: true,
      parentPlanet: jupiterId,
      composition: ["silicates", "dust"],
      surface: {
        surfaceType: SurfaceType.CRATERED,
        proceduralData: {
          color1: "#B22222",
          color2: "#B22222",
          color3: "#B22222",
          color4: "#B22222",
          color5: "#B22222",
          planetType: PlanetType.ROCKY_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Thebe
  actions.addCelestial({
    id: "thebe",
    parentId: jupiterId,
    name: "Thebe",
    type: CelestialType.MOON,
    realMass_kg: 4.3e17,
    realRadius_m: 49.3 * KM,
    temperature: 120,
    albedo: 0.05,
    siderealRotationPeriod_s: 0.6745 * 24 * 60 * 60,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 221900 * KM,
      eccentricity: 0.018,
      inclination: 1.076 * DEG_TO_RAD,
      meanAnomaly: 0,
      argumentOfPeriapsis: 0,
      longitudeOfAscendingNode: 0,
      period_s: 0.6745 * 24 * 60 * 60,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ROCKY_WORLD,
      isMoon: true,
      parentPlanet: jupiterId,
      composition: ["silicates", "dust"],
      surface: {
        surfaceType: SurfaceType.CRATERED,
        proceduralData: {
          color1: "#A0522D",
          color2: "#A0522D",
          color3: "#A0522D",
          color4: "#A0522D",
          color5: "#A0522D",
          planetType: PlanetType.ROCKY_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Adrastea
  actions.addCelestial({
    id: "adrastea",
    name: "Adrastea",
    seed: "adrastea",
    type: CelestialType.MOON,
    parentId: jupiterId,
    realMass_kg: 1.91e16,
    realRadius_m: 8200,
    temperature: 120,
    albedo: 0.05,
    siderealRotationPeriod_s: 0.29826 * 86400,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 129000 * KM,
      eccentricity: 0.0,
      inclination: 0.0,
      longitudeOfAscendingNode: 0.0,
      argumentOfPeriapsis: 0.0,
      meanAnomaly: 214.5 * DEG_TO_RAD,
      period_s: 0.29826 * 86400,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ROCKY_WORLD,
      isMoon: true,
      parentPlanet: jupiterId,
      composition: ["rock", "ice"],
      surface: {
        surfaceType: SurfaceType.CRATERED,
        proceduralData: {
          color1: "#C2B280",
          color2: "#C2B280",
          color3: "#C2B280",
          color4: "#C2B280",
          color5: "#C2B280",
          planetType: PlanetType.ROCKY_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Metis
  actions.addCelestial({
    id: "metis",
    name: "Metis",
    seed: "metis",
    type: CelestialType.MOON,
    parentId: jupiterId,
    realMass_kg: 9.56e16,
    realRadius_m: 21500,
    temperature: 120,
    albedo: 0.05,
    siderealRotationPeriod_s: 0.294779 * 86400,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 128000 * KM,
      eccentricity: 0.0,
      inclination: 0.0,
      longitudeOfAscendingNode: 0.0,
      argumentOfPeriapsis: 0.0,
      meanAnomaly: 166.0 * DEG_TO_RAD,
      period_s: 0.294779 * 86400,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ROCKY_WORLD,
      isMoon: true,
      parentPlanet: jupiterId,
      composition: ["silicates", "water ice"],
      surface: {
        surfaceType: SurfaceType.CRATERED,
        proceduralData: {
          color1: "#C2B280",
          color2: "#C2B280",
          color3: "#C2B280",
          color4: "#C2B280",
          color5: "#C2B280",
          planetType: PlanetType.ROCKY_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Himalia
  actions.addCelestial({
    id: "himalia",
    parentId: jupiterId,
    name: "Himalia",
    type: CelestialType.MOON,
    realMass_kg: 4.2e18,
    realRadius_m: 85 * KM,
    temperature: 120,
    albedo: 0.05,
    siderealRotationPeriod_s: 0.324 * 24 * 60 * 60,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 11461000 * KM,
      eccentricity: 0.162,
      inclination: 27.5 * DEG_TO_RAD,
      meanAnomaly: 0,
      argumentOfPeriapsis: 0,
      longitudeOfAscendingNode: 0,
      period_s: 0.324 * 24 * 60 * 60,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ROCKY_WORLD,
      isMoon: true,
      parentPlanet: jupiterId,
      composition: ["silicates"],
      surface: {
        surfaceType: SurfaceType.CRATERED,

        proceduralData: {
          color1: "#808080",
          color2: "#808080",
          color3: "#808080",
          color4: "#808080",
          color5: "#808080",
          planetType: PlanetType.ROCKY_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Elara
  actions.addCelestial({
    id: "elara",
    parentId: jupiterId,
    name: "Elara",
    type: CelestialType.MOON,
    realRadius_m: 43 * KM,
    realMass_kg: 8.7e17,
    temperature: 120,
    albedo: 0.05,
    siderealRotationPeriod_s: 0.5 * 24 * 60 * 60,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 11741000 * KM,
      eccentricity: 0.217,
      inclination: 26.63 * DEG_TO_RAD,
      meanAnomaly: 0,
      argumentOfPeriapsis: 0,
      longitudeOfAscendingNode: 0,
      period_s: 259.64 * 24 * 60 * 60,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ROCKY_WORLD,
      isMoon: true,
      parentPlanet: jupiterId,
      composition: ["silicates"],
      surface: {
        surfaceType: SurfaceType.CRATERED,
        proceduralData: {
          color1: "#8B8B83",
          color2: "#8B8B83",
          color3: "#8B8B83",
          color4: "#8B8B83",
          color5: "#8B8B83",
          planetType: PlanetType.ROCKY_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Pasiphae
  actions.addCelestial({
    id: "pasiphae",
    parentId: jupiterId,
    name: "Pasiphae",
    type: CelestialType.MOON,
    realRadius_m: 30 * KM,
    realMass_kg: 3.0e17,
    temperature: 120,
    albedo: 0.05,
    siderealRotationPeriod_s: 0.428 * 24 * 60 * 60,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 23624000 * KM,
      eccentricity: 0.409,
      inclination: 151.4 * DEG_TO_RAD,
      meanAnomaly: 0,
      argumentOfPeriapsis: 0,
      longitudeOfAscendingNode: 0,
      period_s: -735 * 24 * 60 * 60, // Retrograde
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ROCKY_WORLD,
      isMoon: true,
      parentPlanet: jupiterId,
      composition: ["silicates"],
      surface: {
        surfaceType: SurfaceType.CRATERED,
        proceduralData: {
          color1: "#A9A9A9",
          color2: "#A9A9A9",
          color3: "#A9A9A9",
          color4: "#A9A9A9",
          color5: "#A9A9A9",
          planetType: PlanetType.ROCKY_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Sinope
  actions.addCelestial({
    id: "sinope",
    parentId: jupiterId,
    name: "Sinope",
    type: CelestialType.MOON,
    realRadius_m: 19 * KM,
    realMass_kg: 7.5e16,
    temperature: 120,
    albedo: 0.05,
    siderealRotationPeriod_s: 0.531 * 24 * 60 * 60,
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 23939000 * KM,
      eccentricity: 0.25,
      inclination: 158.1 * DEG_TO_RAD,
      meanAnomaly: 0,
      argumentOfPeriapsis: 0,
      longitudeOfAscendingNode: 0,
      period_s: -758 * 24 * 60 * 60, // Retrograde
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ROCKY_WORLD,
      isMoon: true,
      parentPlanet: jupiterId,
      composition: ["silicates"],
      surface: {
        surfaceType: SurfaceType.CRATERED,
        proceduralData: {
          color1: "#D2691E",
          color2: "#D2691E",
          color3: "#D2691E",
          color4: "#D2691E",
          color5: "#D2691E",
          planetType: PlanetType.ROCKY_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Lysithea
  actions.addCelestial({
    id: "lysithea",
    parentId: jupiterId,
    name: "Lysithea",
    type: CelestialType.MOON,
    realRadius_m: 18 * KM,
    realMass_kg: 6.3e16,
    temperature: 120,
    albedo: 0.05,
    siderealRotationPeriod_s: 0, // Unknown
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 11717000 * KM,
      eccentricity: 0.112,
      inclination: 28.3 * DEG_TO_RAD,
      meanAnomaly: 0,
      argumentOfPeriapsis: 0,
      longitudeOfAscendingNode: 0,
      period_s: 259.2 * 24 * 60 * 60,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ROCKY_WORLD,
      isMoon: true,
      parentPlanet: jupiterId,
      composition: ["silicates"],
      surface: {
        surfaceType: SurfaceType.CRATERED,
        proceduralData: {
          color1: "#BEBEBE",
          color2: "#BEBEBE",
          color3: "#BEBEBE",
          color4: "#BEBEBE",
          color5: "#BEBEBE",
          planetType: PlanetType.ROCKY_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Carme
  actions.addCelestial({
    id: "carme",
    parentId: jupiterId,
    name: "Carme",
    type: CelestialType.MOON,
    realRadius_m: 23 * KM,
    realMass_kg: 1.3e17,
    temperature: 120,
    albedo: 0.05,
    siderealRotationPeriod_s: 0, // Unknown
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 23404000 * KM,
      eccentricity: 0.253,
      inclination: 164.9 * DEG_TO_RAD,
      meanAnomaly: 0,
      argumentOfPeriapsis: 0,
      longitudeOfAscendingNode: 0,
      period_s: -702 * 24 * 60 * 60, // Retrograde
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ROCKY_WORLD,
      isMoon: true,
      parentPlanet: jupiterId,
      composition: ["silicates"],
      surface: {
        surfaceType: SurfaceType.CRATERED,
        proceduralData: {
          color1: "#F5DEB3",
          color2: "#F5DEB3",
          color3: "#F5DEB3",
          color4: "#F5DEB3",
          color5: "#F5DEB3",
          planetType: PlanetType.ROCKY_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Ananke
  actions.addCelestial({
    id: "ananke",
    parentId: jupiterId,
    name: "Ananke",
    type: CelestialType.MOON,
    realRadius_m: 14 * KM,
    realMass_kg: 3.0e16,
    temperature: 120,
    albedo: 0.05,
    siderealRotationPeriod_s: 0, // Unknown
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 21276000 * KM,
      eccentricity: 0.244,
      inclination: 148.9 * DEG_TO_RAD,
      meanAnomaly: 0,
      argumentOfPeriapsis: 0,
      longitudeOfAscendingNode: 0,
      period_s: -610 * 24 * 60 * 60, // Retrograde
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ROCKY_WORLD,
      isMoon: true,
      parentPlanet: jupiterId,
      composition: ["silicates"],
      surface: {
        surfaceType: SurfaceType.CRATERED,
        proceduralData: {
          color1: "#BC8F8F",
          color2: "#BC8F8F",
          color3: "#BC8F8F",
          color4: "#BC8F8F",
          color5: "#BC8F8F",
          planetType: PlanetType.ROCKY_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });

  // Leda
  actions.addCelestial({
    id: "leda",
    parentId: jupiterId,
    name: "Leda",
    type: CelestialType.MOON,
    realRadius_m: 10 * KM,
    realMass_kg: 1.1e16,
    temperature: 120,
    albedo: 0.05,
    siderealRotationPeriod_s: 0, // Unknown
    axialTilt: defaultMoonAxialTilt,
    orbit: {
      realSemiMajorAxis_m: 11165000 * KM,
      eccentricity: 0.164,
      inclination: 27.46 * DEG_TO_RAD,
      meanAnomaly: 0,
      argumentOfPeriapsis: 0,
      longitudeOfAscendingNode: 0,
      period_s: 240.92 * 24 * 60 * 60,
    },
    properties: {
      type: CelestialType.MOON,
      planetType: PlanetType.ROCKY_WORLD,
      isMoon: true,
      parentPlanet: jupiterId,
      composition: ["silicates"],
      surface: {
        surfaceType: SurfaceType.CRATERED,
        proceduralData: {
          color1: "#D3D3D3",
          color2: "#D3D3D3",
          color3: "#D3D3D3",
          color4: "#D3D3D3",
          color5: "#D3D3D3",
          planetType: PlanetType.ROCKY_WORLD,
          persistence: 0.5,
          lacunarity: 2.0,
          simplePeriod: 5.0,
          octaves: 5,
          bumpScale: 0.3,
          height1: 0,
          height2: 0.25,
          height3: 0.5,
          height4: 0.75,
          height5: 1,
          shininess: 0.1,
          specularStrength: 0.1,
          roughness: 0.8,
          ambientLightIntensity: 0.1,
          undulation: 0.1,
          terrainType: 1,
          terrainAmplitude: 0.3,
          terrainSharpness: 0.7,
          terrainOffset: 0,
        },
      },
    } as PlanetProperties,
  });
}
