import { createOrbitalElements, kmToM } from "@teskooano/core-physics";
import {
  CelestialStatus,
  CelestialType,
  PlanetType,
  type CelestialObject,
  type PlanetProperties,
} from "@teskooano/data-types";

/**
 * Ceres dwarf planet configuration object for modular solar system initialization.
 */
export const ceres: CelestialObject<PlanetProperties> = {
  id: "ceres",
  name: "Ceres",
  seed: "ceres",
  type: CelestialType.DWARF_PLANET,
  status: CelestialStatus.ACTIVE,
  parentId: "sun",
  realMass_kg: 9.3839e20,
  realRadius_m: kmToM(469.7),
  temperature: 172.5,
  albedo: 0.09,
  orbit: createOrbitalElements({
    semiMajorAxisAU: 2.77,
    eccentricity: 0.0785,
    inclinationDeg: 10.6,
    longitudeOfAscendingNodeDeg: 80.3,
    argumentOfPeriapsisDeg: 73.6,
    meanAnomalyDeg: 291.4,
    period_s: 4.60358 * 365.25 * 24 * 3600,
    siderealRotationPeriod_s: 9.07417 * 3600,
    axialTiltDeg: 4.0,
    epoch: "JD 2459600.5",
  }),
  properties: {
    type: CelestialType.DWARF_PLANET,
    classType: PlanetType.ROCKY,
    isMoon: false,
    composition: [
      "water ice",
      "hydrated minerals",
      "carbonates",
      "clay minerals",
      "salts",
      "carbonaceous material",
      "organic compounds",
    ],
    atmosphere: undefined,
    surface: {
      roughness: 0.9,
      persistence: 0.6,
      lacunarity: 2.3,
      simplePeriod: 3.2,
      octaves: 8,
      bumpScale: 3.0,
      color1: "#2A1F1A",
      color2: "#3D2B24",
      color3: "#4A3528",
      color4: "#5A4030",
      color5: "#6B4A38",
      height1: 0.05,
      height2: 0.2,
      height3: 0.4,
      height4: 0.65,
      height5: 0.85,
      shininess: 4,
      specularStrength: 0.04,
      ambientLightIntensity: 0.02,
      undulation: 0.4,
      terrainType: 2,
      terrainAmplitude: 0.9,
      terrainSharpness: 1.6,
      terrainOffset: -0.15,
    },
  },
};
