import { createOrbitalElements, kmToM } from "@teskooano/core-physics";
import {
  type CelestialObject,
  CelestialStatus,
  CelestialType,
  PlanetType,
  type PlanetProperties,
} from "@teskooano/data-types";

/**
 * Eris dwarf planet configuration object for modular solar system initialization.
 */
export const eris: CelestialObject<PlanetProperties> = {
  id: "eris",
  name: "Eris",
  seed: "eris",
  type: CelestialType.DWARF_PLANET,
  status: CelestialStatus.ACTIVE,
  parentId: "sun",
  realMass_kg: 1.66e22,
  realRadius_m: kmToM(1163),
  temperature: 30,
  albedo: 0.96,
  orbit: createOrbitalElements({
    semiMajorAxisAU: 67.668,
    eccentricity: 0.44177,
    inclinationDeg: 44.187,
    longitudeOfAscendingNodeDeg: 35.875,
    argumentOfPeriapsisDeg: 151.431,
    meanAnomalyDeg: 197.634,
    period_s: 2.045e10,
    siderealRotationPeriod_s: 25.9 * 3600,
    axialTiltDeg: 0.0,
  }),
  properties: {
    type: CelestialType.DWARF_PLANET,
    classType: PlanetType.BARREN,
    isMoon: false,
    composition: [
      "nitrogen ice",
      "methane ice",
      "water ice",
      "rocky core",
      "carbon monoxide",
    ],
    atmosphere: {
      glowColor: "#E0E0FF",
      intensity: 0.02,
      power: 0.4,
      thickness: 0.01,
    },
    surface: {
      roughness: 0.15,
      persistence: 0.48,
      lacunarity: 2.0,
      simplePeriod: 1.5,
      octaves: 7,
      bumpScale: 1.2,
      color1: "#E8E8FF",
      color2: "#F0F0FF",
      color3: "#F5F5FF",
      color4: "#FAFAFF",
      color5: "#FFFFFF",
      height1: 0.1,
      height2: 0.3,
      height3: 0.5,
      height4: 0.75,
      height5: 0.9,
      shininess: 45,
      specularStrength: 0.85,
      ambientLightIntensity: 0.01,
      undulation: 0.08,
      terrainType: 1,
      terrainAmplitude: 0.3,
      terrainSharpness: 0.8,
      terrainOffset: 0.1,
    },
  },
};

/**
 * Dysnomia moon configuration object for modular solar system initialization.
 */
export const dysnomia: CelestialObject<PlanetProperties> = {
  id: "dysnomia",
  name: "Dysnomia",
  seed: "dysnomia",
  type: CelestialType.MOON,
  status: CelestialStatus.ACTIVE,
  parentId: "eris",
  realMass_kg: 3.5e18,
  realRadius_m: kmToM(175),
  temperature: 30,
  albedo: 0.15,
  orbit: createOrbitalElements({
    semiMajorAxisAU: 0.00025,
    eccentricity: 0.0062,
    inclinationDeg: 142.0,
    longitudeOfAscendingNodeDeg: 139.0,
    argumentOfPeriapsisDeg: 194.0,
    meanAnomalyDeg: 265.0,
    period_s: 15.786 * 24 * 3600,
    siderealRotationPeriod_s: 15.786 * 24 * 3600,
    axialTiltDeg: 0,
  }),
  properties: {
    type: CelestialType.MOON,
    classType: PlanetType.BARREN,
    isMoon: true,
    composition: ["water ice", "rocky material"],
    shapeModel: "asteroid",
    atmosphere: {
      glowColor: "#000000",
      intensity: 0,
      power: 0,
      thickness: 0,
    },
    surface: {
      roughness: 0.9,
      persistence: 0.5,
      lacunarity: 2.2,
      simplePeriod: 3.5,
      octaves: 8,
      bumpScale: 3.0,
      color1: "#404040",
      color2: "#505050",
      color3: "#606060",
      color4: "#707070",
      color5: "#808080",
      height1: 0.0,
      height2: 0.25,
      height3: 0.5,
      height4: 0.75,
      height5: 1.0,
      shininess: 2,
      specularStrength: 0.05,
      ambientLightIntensity: 0.01,
      undulation: 0.4,
      terrainType: 1,
      terrainAmplitude: 0.8,
      terrainSharpness: 1.5,
      terrainOffset: 0.0,
    },
  },
};
