import { createOrbitalElements, kmToM } from "@teskooano/core-physics";
import {
  type CelestialObject,
  CelestialType,
  PlanetType,
  CelestialStatus,
  type PlanetProperties,
} from "@teskooano/data-types";

/**
 * Makemake dwarf planet configuration object for modular solar system initialization.
 */
export const makemake: CelestialObject<PlanetProperties> = {
  id: "makemake",
  name: "Makemake",
  seed: "makemake",
  type: CelestialType.DWARF_PLANET,
  status: CelestialStatus.ACTIVE,
  parentId: "sun",
  realMass_kg: 3.1e21,
  realRadius_m: kmToM(715),
  temperature: 34,
  albedo: 0.82,
  orbit: createOrbitalElements({
    semiMajorAxisAU: 45.43,
    eccentricity: 0.16126,
    inclinationDeg: 28.9835,
    longitudeOfAscendingNodeDeg: 79.62,
    argumentOfPeriapsisDeg: 294.834,
    meanAnomalyDeg: 165.514,
    period_s: 306.21 * 365.25 * 24 * 3600,
    siderealRotationPeriod_s: 22.8266 * 3600,
    axialTiltDeg: 0.0,
    epoch: "JD 2458900.5",
  }),
  properties: {
    type: CelestialType.DWARF_PLANET,
    classType: PlanetType.BARREN,
    isMoon: false,
    composition: [
      "methane ice",
      "nitrogen ice",
      "water ice",
      "rocky core",
      "ethane",
      "tholins",
      "frozen gases",
    ],
    atmosphere: undefined,
    surface: {
      roughness: 0.1,
      persistence: 0.3,
      lacunarity: 1.8,
      simplePeriod: 1.5,
      octaves: 5,
      bumpScale: 0.5,
      color1: "#F8F8FF",
      color2: "#F0F0FF",
      color3: "#E8E8FF",
      color4: "#E0E0FF",
      color5: "#D8D8FF",
      height1: 0.1,
      height2: 0.25,
      height3: 0.4,
      height4: 0.6,
      height5: 0.8,
      shininess: 90,
      specularStrength: 0.7,
      ambientLightIntensity: 0.02,
      undulation: 0.1,
      terrainType: 1,
      terrainAmplitude: 0.2,
      terrainSharpness: 0.5,
      terrainOffset: 0.1,
    },
  },
};

/**
 * MK2 moon configuration object for modular solar system initialization.
 */
export const mk2: CelestialObject<PlanetProperties> = {
  id: "mk2",
  name: "MK2",
  seed: "mk2",
  type: CelestialType.MOON,
  status: CelestialStatus.ACTIVE,
  parentId: "makemake",
  realMass_kg: 1.0e17,
  realRadius_m: kmToM(175),
  temperature: 30,
  albedo: 0.04,
  orbit: createOrbitalElements({
    semiMajorAxisAU: 0.00014,
    eccentricity: 0.0,
    inclinationDeg: 75.0,
    longitudeOfAscendingNodeDeg: 0.0,
    argumentOfPeriapsisDeg: 0.0,
    meanAnomalyDeg: 0.0,
    period_s: 12.4 * 24 * 3600,
    siderealRotationPeriod_s: 12.4 * 24 * 3600,
    axialTiltDeg: 0,
  }),
  properties: {
    type: CelestialType.MOON,
    classType: PlanetType.BARREN,
    isMoon: true,
    composition: [
      "water ice",
      "rocky material",
      "organic compounds",
      "carbonaceous material",
      "tholins",
    ],
    shapeModel: "asteroid",
    atmosphere: undefined,
    surface: {
      roughness: 0.9,
      persistence: 0.7,
      lacunarity: 2.5,
      simplePeriod: 4.5,
      octaves: 8,
      bumpScale: 4.0,
      color1: "#101010",
      color2: "#151515",
      color3: "#202020",
      color4: "#252525",
      color5: "#303030",
      height1: 0.0,
      height2: 0.15,
      height3: 0.35,
      height4: 0.55,
      height5: 0.75,
      shininess: 1,
      specularStrength: 0.02,
      ambientLightIntensity: 0.01,
      undulation: 0.6,
      terrainType: 1,
      terrainAmplitude: 1.2,
      terrainSharpness: 2.0,
      terrainOffset: -0.2,
    },
  },
};
