import { createOrbitalElements, kmToM } from "@teskooano/core-physics";
import {
  CelestialType,
  PlanetType,
  CelestialStatus,
  type PlanetProperties,
  type CelestialObject,
} from "@teskooano/data-types";

/**
 * Pallas asteroid configuration object for modular solar system initialization.
 */
export const pallas: CelestialObject<PlanetProperties> = {
  id: "pallas",
  name: "2 Pallas",
  seed: "pallas",
  type: CelestialType.DWARF_PLANET,
  status: CelestialStatus.ACTIVE,
  parentId: "sun",
  realMass_kg: 2.11e20,
  realRadius_m: kmToM(256),
  temperature: 160,
  albedo: 0.155,
  orbit: createOrbitalElements({
    semiMajorAxisAU: 2.77,
    eccentricity: 0.231,
    inclinationDeg: 34.84,
    longitudeOfAscendingNodeDeg: 173.1,
    argumentOfPeriapsisDeg: 310.3,
    meanAnomalyDeg: 113.7,
    period_s: 1.681e8,
    siderealRotationPeriod_s: 28080,
    axialTiltDeg: 84,
  }),
  properties: {
    type: CelestialType.DWARF_PLANET,
    classType: PlanetType.ROCKY,
    isMoon: false,
    composition: [
      "carbonaceous chondrite",
      "B-type asteroid material",
      "primitive material",
      "organic compounds",
    ],
    surface: {
      roughness: 0.8,
      persistence: 0.6,
      lacunarity: 2.2,
      simplePeriod: 2.8,
      octaves: 8,
      bumpScale: 2.5,
      color1: "#404040",
      color2: "#505050",
      color3: "#696969",
      color4: "#808080",
      color5: "#A0A0A0",
      height1: 0.1,
      height2: 0.3,
      height3: 0.5,
      height4: 0.7,
      height5: 0.9,
      shininess: 4,
      specularStrength: 0.05,
      ambientLightIntensity: 0.01,
      undulation: 0.5,
      terrainType: 1,
      terrainAmplitude: 1.0,
      terrainSharpness: 1.5,
      terrainOffset: 0.0,
    },
  },
};
