import { createOrbitalElements, kmToM } from "@teskooano/core-physics";
import {
  type CelestialObject,
  CelestialType,
  PlanetType,
  CelestialStatus,
  type PlanetProperties,
} from "@teskooano/data-types";

/**
 * Vesta asteroid configuration object for modular solar system initialization.
 */
export const vesta: CelestialObject<PlanetProperties> = {
  id: "vesta",
  name: "4 Vesta",
  seed: "vesta",
  type: CelestialType.DWARF_PLANET,
  status: CelestialStatus.ACTIVE,
  parentId: "sun",
  realMass_kg: 2.59e20,
  realRadius_m: kmToM(262.7),
  temperature: 150,
  albedo: 0.423,
  orbit: createOrbitalElements({
    semiMajorAxisAU: 2.36,
    eccentricity: 0.089,
    inclinationDeg: 7.14,
    longitudeOfAscendingNodeDeg: 103.9,
    argumentOfPeriapsisDeg: 151.2,
    meanAnomalyDeg: 20.8,
    period_s: 1.145e8,
    siderealRotationPeriod_s: 19200,
    axialTiltDeg: 29,
  }),
  properties: {
    type: CelestialType.DWARF_PLANET,
    classType: PlanetType.ROCKY,
    isMoon: false,
    composition: [
      "basaltic rock",
      "pyroxene",
      "olivine",
      "differentiated interior",
    ],
    surface: {
      roughness: 0.7,
      persistence: 0.55,
      lacunarity: 2.0,
      simplePeriod: 2.2,
      octaves: 7,
      bumpScale: 2.0,
      color1: "#654321",
      color2: "#8B7355",
      color3: "#A0522D",
      color4: "#CD853F",
      color5: "#DEB887",
      height1: 0.1,
      height2: 0.3,
      height3: 0.5,
      height4: 0.7,
      height5: 0.9,
      shininess: 8,
      specularStrength: 0.15,
      ambientLightIntensity: 0.01,
      undulation: 0.4,
      terrainType: 2,
      terrainAmplitude: 0.8,
      terrainSharpness: 1.2,
      terrainOffset: 0.0,
    },
  },
};
